### ISSUE TITLE
[BUG] some stack-traces (OOM, CertPathValidatorException, ProtocolException, IllegalArgumentException "invalid checksum", SocketException)

### ISSUE THREAD

**Issue by cobratbq** [vitorpamplona/amethyst#981]
**Describe the bug**
As discussed earlier. I would drop some stack-traces if I found any.

[crashes-amethyst.txt](https://github.com/user-attachments/files/16258256/crashes-amethyst.txt)

**To Reproduce**
Various occurrences. No strict reproduction recipe available, but stack-traces themselves hint at events that may occur.

**Expected behavior**
As discussed before, this gives some insight into what exceptions slip through that might be handled.

**Video and Screenshots**
Nope.

**Device (please complete the following information):**
- Google Pixel 6 Pro,
- Android 14
- 0.88.8 (from F-Droid)

**Bounty (in Bitcoin sats) offered for a solution**
Nope, sorry. At this point, I'm providing the stack-traces in case you'd like the insight. Feel free to send me some for my service. ;-)

**Comment by KotlinGeekDev** [comment]
Please @cobratbq does this occur on the latest version?

**Comment by KotlinGeekDev** [comment]
Please @vitorpamplona maybe this was fixed already?(given your recent Nostr posts about the memory occupied by Amethyst data?)

**Comment by cobratbq** [comment]
> Please @cobratbq does this occur on the latest version?

I will check soon to see what stack-traces have popped up recently. They probably won't be the same, but I'll add a dump if they seem relevant.

**Comment by cobratbq** [comment]
I just checked ... the certificate trust-path exceptions still show, the socketexceptions still show. There is a `SocketTimeoutException` that I haven't seen last time.

In general, it looks cleaner. Note that I disabled automatic video loading, which always made things more fragile for me in the past.

**Comment by KotlinGeekDev** [comment]
These seem to just be normal app activity(some relays being unavailable or disconnecting, etc...). 
There's no problem with those errors. They are things that happen. :)

**Comment by KotlinGeekDev** [comment]
Please @vitorpamplona I think this issue can be closed.

**Comment by cobratbq** [comment]
> These seem to just be normal app activity(some relays being unavailable or disconnecting, etc...). There's no problem with those errors. They are things that happen. :)

Sorry, I had missed your reply in the notifications. Yes they are. My intention is that you might want to catch these exceptions and log a message instead. It seems a decision is made and that's all that is needed. I brought them to your attention to provide you with input from regular use-cases in case you might discover something.

Thanks!
